const DRAFT = 'DRAFT';
const PENDING_NOTARY = 'PENDING_NOTARY';
const WAITING_FOR_SIGNERS = 'WAITING_FOR_SIGNERS';
const WAITING_FOR_NOTARY_SIGNATURE = 'WAITING_FOR_NOTARY_SIGNATURE';
const SUBMITTED = 'SUBMITTED';
const CONFIRMED = 'CONFIRMED';
const FAILED = 'FAILED';
const REJECTED = 'REJECTED';
module.exports = {
    DRAFT,
PENDING_NOTARY,
WAITING_FOR_SIGNERS,
WAITING_FOR_NOTARY_SIGNATURE,
SUBMITTED,
CONFIRMED,
FAILED,
REJECTED
};

